Updated test-unit.yml to comment a coverage report
Signed-off-by: Tanner Jones <alltechguyblog@gmail.com>

diff --git a/.github/workflows/test-unit.yml b/.github/workflows/test-unit.yml
--- a/.github/workflows/test-unit.yml
+++ b/.github/workflows/test-unit.yml
@@ -18,14 +18,19 @@ jobs:
       - uses: actions/checkout@v3
         with: { fetch-depth: 1 }
       - uses: actions/setup-go@v3
-        with: { go-version: "${{ matrix.go }}" }
-      - run: go version
-      - run: make test-unit race=true
-      - uses: codecov/codecov-action@v1
         with:
-          file: tmp/unit.cov
-          flags: unit
-        if: matrix.os == 'ubuntu-latest'
+          go-version: "${{ matrix.go }}"
+      - run: go version
+      - run: make test-unit-with-coverage race=true
+      - name: Upload coverage report
+        uses: codecov/codecov-action@v1
+        with:
+          file: coverage.out
+      - name: Comment coverage report
+        run: |
+          if [ "${{ matrix.os }}" == "ubuntu-latest" ]; then # will only run on ubuntu
+            curl -sSfL https://codecov.io/bash | bash -s -- -Z -K -f coverage.out || echo "Codecov upload failed"
+          fi      
 
   bench:
     name: Benchmarks
@@ -34,6 +39,7 @@ jobs:
       - uses: actions/checkout@v3
         with: { fetch-depth: 1 }
       - uses: actions/setup-go@v3
-        with: { go-version: '1.x' }
+        with:
+          go-version: '1.x'
       - run: go version
       - run: make test-bench
