Updated test-unit make command to include all OSs
Signed-off-by: Tanner Jones <alltechguyblog@gmail.com>

diff --git a/.github/workflows/test-unit.yml b/.github/workflows/test-unit.yml
--- a/.github/workflows/test-unit.yml
+++ b/.github/workflows/test-unit.yml
@@ -28,10 +28,11 @@ jobs:
           file: coverage.out
       - name: Comment coverage report
         run: |
-          if [ "${{ matrix.os }}" == "ubuntu-latest" ]; then # will only run on ubuntu
-            curl -sSfL https://codecov.io/bash | bash -s -- -Z -K -f coverage.out || echo "Codecov upload failed"
-          fi      
-
+          case ${{ matrix.os }} in
+            ubuntu-latest|windows-latest|macOS-latest)
+              curl -sSfL https://codecov.io/bash | bash -s -- -Z -K -f coverage.out || echo "Codecov upload failed"
+              ;;
+          esac
   bench:
     name: Benchmarks
     runs-on: ubuntu-latest
